"""Claude Code target.

Claude has no glob-scoped rule loader, so the language idioms are folded into
``CLAUDE.md`` rather than emitted as separate rule files. Everything else comes
straight from the canonical model.
"""

from __future__ import annotations

import json
from pathlib import Path

from contextkeel.render import mcp as mcp_render
from contextkeel.render.model import CAPABILITIES, ContentBundle, HookDef

CAPS = CAPABILITIES["claude"]


def render(
    *,
    bundle: ContentBundle,
    root: Path,
    vault_dir: Path,
    hooks: list[HookDef],
    allowed_commands: list[str],
) -> dict[str, str]:
    """Return ``relative path -> file content`` for the ``.claude/`` tree."""
    files: dict[str, str] = {}

    files[".claude/CLAUDE.md"] = _claude_md(bundle, vault_dir)

    for skill in bundle.skills:
        front = [f"name: {skill.name}", f"description: {skill.description}"]
        if CAPS.per_skill_invocation_flag and not skill.model_invocable:
            front.append("disable-model-invocation: true")
        files[f".claude/skills/{skill.name}/SKILL.md"] = (
            "---\n" + "\n".join(front) + "\n---\n\n" + skill.body
        )
        for extra_name, extra_body in skill.extras.items():
            files[f".claude/skills/{skill.name}/{extra_name}"] = extra_body

    for command in bundle.commands:
        files[f".claude/commands/{command.name}.md"] = (
            f"---\ndescription: {command.description}\n---\n\n{command.body}"
        )

    if CAPS.supports_agents:
        for agent in bundle.agents:
            front = [f"name: {agent.name}", f"description: {agent.description}"]
            if agent.tools:
                front.append(f"tools: {agent.tools}")
            files[f".claude/agents/{agent.name}.md"] = (
                "---\n" + "\n".join(front) + "\n---\n\n" + agent.body
            )

    files[".claude/settings.json"] = _settings(hooks, allowed_commands)
    files[".mcp.json"] = json.dumps(mcp_render.build(root, vault_dir), indent=2) + "\n"
    return files


def _claude_md(bundle: ContentBundle, vault_dir: Path) -> str:
    rules = "\n\n".join(
        f"### {rule.name}"
        + (f" — applies to `{rule.globs}`" if rule.globs else "")
        + f"\n\n{rule.body.strip()}"
        for rule in bundle.rules
        if not rule.always_apply
    )
    core = "\n".join(r.body.strip() for r in bundle.rules if r.always_apply)
    vault_name = vault_dir.name

    return f"""# CLAUDE.md

Generated by contextkeel — do not edit by hand. Change the source and run
`ckeel sync`; edits here are detected and reported, not silently overwritten.

## Protocol

1. Read `project.yml` for the resolved stack.
2. Read `.contextkeel/index/REPORT.md` and query `.contextkeel/index/index.json`
   **before** scanning source files. That is the whole point: navigate by index
   instead of globbing the repository.
3. Read `{vault_name}/Context/` for the prescriptive rules (Conventions,
   Domain Glossary, API Contracts, Tech Stack).
4. Open only the files the index pointed you at.
5. After meaningful changes run `ckeel sync` so both halves stay true.

{core}

## Language idioms

Claude Code has no glob-scoped rule loader, so apply the relevant section below
based on the file you are editing.

{rules}

## Under the hood

`ckeel internals` names every underlying tool and prints the exact commands
this workspace runs, along with every available override.
"""


def _settings(hooks: list[HookDef], allowed_commands: list[str]) -> str:
    allow = [
        "Read",
        "Edit",
        "Write",
        "Glob",
        "Grep",
        "Bash(git status:*)",
        "Bash(git log:*)",
        "Bash(git diff:*)",
        # The workflow this file mandates must not prompt on every step.
        "Bash(ckeel:*)",
        "Bash(contextkeel:*)",
        *allowed_commands,
    ]
    payload = {
        "permissions": {
            "allow": sorted(set(allow)),
            # Sorted, because the merge in hooks.install sorts too — if the
            # two disagreed, every run would "update" this file forever.
            "deny": sorted(
                [
                    "Read(**/.env)",
                    "Read(**/.env.*)",
                    "Read(**/*.secret)",
                    "Read(**/secrets.json)",
                ]
            ),
        },
        "hooks": _hooks_payload(hooks),
    }
    return json.dumps(payload, indent=2) + "\n"


def _hooks_payload(hooks: list[HookDef]) -> dict:
    grouped: dict[str, list[dict]] = {}
    for hook in hooks:
        grouped.setdefault(hook.event, []).append(
            {
                "matcher": hook.matcher,
                "hooks": [
                    {
                        "type": "command",
                        "command": " ".join(hook.command),
                        "_owner": hook.owner,
                    }
                ],
            }
        )
    return grouped


__all__ = ["CAPS", "render"]
