"""Continue target.

The point of this module is **self-containment**. In the original template
every Continue prompt said "read ``.cursor/skills/<name>/SKILL.md``", so
Continue silently broke whenever ``.cursor/`` was absent. Here each prompt
inlines the playbook it needs, and a reference to another editor's directory
is treated as a build error.

Continue also has no hook system, so hooks are skipped deliberately rather
than emitted in a shape it cannot consume.
"""

from __future__ import annotations

import json
from pathlib import Path

from contextkeel.render import mcp as mcp_render
from contextkeel.render.model import CAPABILITIES, ContentBundle, HookDef

CAPS = CAPABILITIES["continue"]

FOREIGN = (".cursor/", ".claude/")


class CrossToolReference(ValueError):
    """A rendered file referenced another editor's directory."""


def render(
    *,
    bundle: ContentBundle,
    root: Path,
    vault_dir: Path,
    hooks: list[HookDef],  # noqa: ARG001 - Continue has no hook system
    allowed_commands: list[str],  # noqa: ARG001 - no permission model either
) -> dict[str, str]:
    files: dict[str, str] = {}

    for rule in bundle.rules:
        front = [f"name: {rule.name}", f"description: {rule.description}"]
        if rule.globs:
            # Continue's dialect quotes globs; Cursor's does not.
            quoted = f'"{rule.globs}"' if CAPS.frontmatter_quotes_globs else rule.globs
            front.append(f"globs: {quoted}")
        if rule.always_apply:
            front.append("alwaysApply: true")
        files[f".continue/rules/{rule.name}.md"] = (
            "---\n" + "\n".join(front) + "\n---\n\n" + rule.body
        )

    files[".continue/config.yaml"] = _config_yaml(bundle)
    files[".continue/mcpServers/mcp.json"] = (
        json.dumps(mcp_render.build(root, vault_dir), indent=2) + "\n"
    )

    for path, content in files.items():
        for foreign in FOREIGN:
            if foreign in content:
                raise CrossToolReference(
                    f"{path} references {foreign}; Continue configs must be self-contained"
                )
    return files


def _config_yaml(bundle: ContentBundle) -> str:
    lines = [
        "# Generated by contextkeel — do not edit by hand.",
        "# Change the source and run `ckeel sync`.",
        "name: contextkeel workspace",
        "version: 1.0.0",
        "schema: v1",
        "",
        "# Models are per-person: API keys must never be generated into a",
        "# shared, checked-in file. Add your own below.",
        "# models:",
        "#   - name: My model",
        "#     provider: anthropic",
        "#     model: claude-sonnet-5",
        "#     roles: [chat, edit, agent]",
        "",
        "context:",
        "  - name: codebase",
        "  - name: diff",
        "  - name: terminal",
        "  - name: problems",
        "  - name: folder",
        "  - name: tree",
        "  - name: open",
        "",
        "prompts:",
    ]

    by_name = {skill.name: skill for skill in bundle.skills}
    for command in bundle.commands:
        # Inline the playbook so the prompt stands alone.
        skill = _skill_for(command.name, by_name)
        body = command.body.strip()
        if skill is not None:
            body = f"{body}\n\n---\n\n{skill.body.strip()}"
        indented = "\n".join(
            f"      {line}" if line else "" for line in body.splitlines()
        )
        lines.append(f"  - name: {command.name}")
        lines.append(f"    description: {_yaml_scalar(command.description)}")
        lines.append("    prompt: |")
        lines.append(indented)
        lines.append("")

    return "\n".join(lines) + "\n"


def _skill_for(command_name: str, skills: dict) -> object | None:
    aliases = {
        "context": "load-context",
        "sync-context": "update-context",
        "plan": "write-prompt-plan",
        "init": "bootstrap-project",
        "scaffold": "scaffold-feature",
        "test": "run-tests",
        "debug": "debug-issue",
        "review": "review-changes",
        "commit": "write-commit",
        "adr": "record-decision",
    }
    return skills.get(aliases.get(command_name, command_name))


def _yaml_scalar(text: str) -> str:
    cleaned = text.replace('"', "'").strip()
    return f'"{cleaned}"' if cleaned else '""'


__all__ = ["CAPS", "CrossToolReference", "render"]
